### ISSUE TITLE
JSDoc 4.0.0

### ISSUE THREAD

**Issue by mdellanave** [SoftwareBrothers/better-docs#233]
Hi, 
I'm trying to use better-docs (version 2.7.2) in my project with jsdoc 4.0.0 released a few days ago.

I have this error

```
FATAL: Unable to load template: Cannot find module 'taffydb'
Require stack:
- ..\node_modules\better-docs\publish.js
- ..\node_modules\jsdoc\cli.js
- ..\node_modules\jsdoc\jsdoc.js
```

With the previous version 3.6.11 it works.

Does better-docs needs an update to make it works with 4.0.0?

**Comment by jesusiglesias** [comment]
Same problem here.

Yes, better-docs needs an update to support Salty. Otherwise, it is necessary to follow up this guide.

https://github.com/jsdoc/jsdoc/tree/main/packages/jsdoc-salty#use-salty-in-a-jsdoc-template

**Comment by mdellanave** [comment]
Thank you Jesus, is there any contributor who wants to take charge of the changes?

**Comment by kylegrabski** [comment]
THANK YOU FOR THIS!! I just rolled back to jsdoc@3.6.11

**Comment by cunneen** [comment]
Thanks to @drazisil for PR #247 linked above; I can use this with jsdoc@4 as follows:

```
yarn remove better-docs
yarn add -D 'git+https://github.com/drazisil/better-docs/#dfbd2e3158f119d247c2efbf72acc79d1ec4db5c'
```

I'm guessing it'd be something like this if you're using NPM:

```
npm uninstall better-docs
npm add -D 'git+https://github.com/drazisil/better-docs/#dfbd2e3158f119d247c2efbf72acc79d1ec4db5c'
```
