### PR TITLE
Replace taffy with salty

### LINKED ISSUE #233: JSDoc 4.0.0
Hi, 
I'm trying to use better-docs (version 2.7.2) in my project with jsdoc 4.0.0 released a few days ago.

I have this error

```
FATAL: Unable to load template: Cannot find module 'taffydb'
Require stack:
- ..\node_modules\better-docs\publish.js
- ..\node_modules\jsdoc\cli.js
- ..\node_modules\jsdoc\jsdoc.js
```

With the previous version 3.6.11 it works.

Does better-docs needs an update to make it works with 4.0.0?

### PR DESCRIPTION
**Pull request by drazisil**
Fixes #233

### CODE REVIEW

**Comment by trezy** [comment]
I'm bumping this so maybe @ariansobczak-rst or @wojtek-krysiak will take a look?

**Review by ariansobczak-rst — APPROVED** [review]

**Comment by hexxone** [comment]
Bump, a merge would be real nice. 
So we can finally get rid of this outdated, vulnerable package :)

**Comment by hexxone** [comment]
Thank you 🎉
